//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uco.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uco.Models.Resources.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Map.
        /// </summary>
        public static string AddressMap {
            get {
                return ResourceManager.GetString("AddressMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Manual Description.
        /// </summary>
        public static string DeliveryManualDescription {
            get {
                return ResourceManager.GetString("DeliveryManualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Time.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Ship From.
        /// </summary>
        public static string FreeShipFrom {
            get {
                return ResourceManager.GetString("FreeShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Description.
        /// </summary>
        public static string FullDescription {
            get {
                return ResourceManager.GetString("FullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosher.
        /// </summary>
        public static string Kosher {
            get {
                return ResourceManager.GetString("Kosher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Cost.
        /// </summary>
        public static string ShipCost {
            get {
                return ResourceManager.GetString("ShipCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Radius.
        /// </summary>
        public static string ShipRadius {
            get {
                return ResourceManager.GetString("ShipRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Ship Special Times.
        /// </summary>
        public static string ShopShipSpecialTimes {
            get {
                return ResourceManager.GetString("ShopShipSpecialTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Ship Times.
        /// </summary>
        public static string ShopShipTimes {
            get {
                return ResourceManager.GetString("ShopShipTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopType.
        /// </summary>
        public static string ShopType {
            get {
                return ResourceManager.GetString("ShopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Work Special Times.
        /// </summary>
        public static string ShopWorkSpecialTimes {
            get {
                return ResourceManager.GetString("ShopWorkSpecialTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Work Times.
        /// </summary>
        public static string ShopWorkTimes {
            get {
                return ResourceManager.GetString("ShopWorkTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Categories.
        /// </summary>
        public static string TabCategories {
            get {
                return ResourceManager.GetString("TabCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string TabContent {
            get {
                return ResourceManager.GetString("TabContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string TabMain {
            get {
                return ResourceManager.GetString("TabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string TabProduct {
            get {
                return ResourceManager.GetString("TabProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string TabProducts {
            get {
                return ResourceManager.GetString("TabProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiping.
        /// </summary>
        public static string TabShiping {
            get {
                return ResourceManager.GetString("TabShiping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Shop Ship Special Times.
        /// </summary>
        public static string TabShopShipSpecialTimes {
            get {
                return ResourceManager.GetString("TabShopShipSpecialTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Shop Ship Times.
        /// </summary>
        public static string TabShopShipTimes {
            get {
                return ResourceManager.GetString("TabShopShipTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopType.
        /// </summary>
        public static string TabShopType {
            get {
                return ResourceManager.GetString("TabShopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Shop Work Special Times.
        /// </summary>
        public static string TabShopWorkSpecialTimes {
            get {
                return ResourceManager.GetString("TabShopWorkSpecialTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Shop Work Times.
        /// </summary>
        public static string TabShopWorkTimes {
            get {
                return ResourceManager.GetString("TabShopWorkTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
